/**
 * edit.js
 *
 * Editor component for the Leaflet Map Block.
 *
 * ARCHITECTURE: CLIENT-SIDE LEAFLET RENDERING
 * ─────────────────────────────────────────────
 * The editor renders a real, interactive Leaflet map directly via L.map().
 * There is no ServerSideRender, no shortcode output in the editor, and no
 * script-cloning. The shortcodes ([leaflet-map], [leaflet-marker], …) are
 * only generated by render.php for the frontend visitor.
 *
 * FRAME CONTEXT (WP 6.3+ iframed editor)
 * ───────────────────────────────────────
 * - This editorScript runs in the OUTER admin frame.
 * - The block DOM is portaled into the IFRAME by React.
 * - mapContainerRef.current is therefore a node in the IFRAME document.
 * - We access the iframe's Leaflet via:
 *     mapContainerRef.current.ownerDocument.defaultView.L
 * - Tile configuration (bflmConfig) is injected into the iframe window by
 *   PHP via wp_add_inline_script on the `leaflet_js` handle.
 *
 * EFFECTS OVERVIEW
 * ────────────────
 * 1. [mount]           Initialize Leaflet map, tile layer, marker layer group.
 *                      Polls for L if not yet available (async iframe load).
 *                      Also adds the initial markers from attributes.
 * 2. [lat, lng, zoom]  Sync sidebar → map (setView). Guarded by
 *                      isProgrammaticMoveRef to avoid echo with Effect 1's
 *                      moveend listener.
 * 3. [height]          invalidateSize after container CSS change.
 * 4. [scrollWheelZoom] enable / disable scroll-wheel zoom handler.
 * 5. [zoomControl]     add / remove the +/- zoom control widget.
 * 6. [markers]         Clear marker layer group and re-add all markers from
 *                      the attribute array as draggable L.marker instances.
 *    (no deps)         Keep markersRef in sync with the latest markers array
 *                      so that dragend closures never see stale state.
 *
 * FEEDBACK LOOP PREVENTION
 * ─────────────────────────
 * User pans/zooms → moveend → setAttributes(lat/lng/zoom) → Effect 2 fires.
 * Guard: isProgrammaticMoveRef is set to true before the programmatic setView
 * call and cleared immediately after (setView with animate:false fires moveend
 * synchronously, so the guard works without a timeout).
 *
 * @package BlocksForLeafletMap
 */

import { __, sprintf } from '@wordpress/i18n';
import { useEffect, useRef } from '@wordpress/element';
import { useBlockProps, InspectorControls } from '@wordpress/block-editor';
import {
	PanelBody,
	Button,
	__experimentalNumberControl as NumberControl,
	RangeControl,
	ToggleControl,
	TextControl,
	TextareaControl,
} from '@wordpress/components';

import './editor.scss';

/** Default tile URL — same as the Leaflet Map plugin default. */
const DEFAULT_TILE_URL    = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png';
const DEFAULT_ATTRIBUTION = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';

/**
 * Edit component for the Leaflet Map Block.
 *
 * @param {Object}   props               Component props.
 * @param {Object}   props.attributes    Block attributes.
 * @param {Function} props.setAttributes Attribute setter.
 * @return {Element} Element to render.
 */
export default function Edit( { attributes, setAttributes } ) {
	const {
		lat,
		lng,
		zoom,
		height,
		scrollWheelZoom,
		zoomControl,
		markers,
	} = attributes;

	/** Container div that Leaflet owns as its map root. */
	const mapContainerRef = useRef( null );

	/** Live Leaflet map instance. */
	const mapInstanceRef = useRef( null );

	/** L.layerGroup holding all editor marker instances. */
	const markerLayerGroupRef = useRef( null );

	/**
	 * Set to true immediately before a programmatic map.setView() call so
	 * the moveend listener in Effect 1 does not echo the change back into
	 * setAttributes. Cleared right after setView returns (synchronously).
	 *
	 * @type {React.MutableRefObject<boolean>}
	 */
	const isProgrammaticMoveRef = useRef( false );

	/** setTimeout handle for the 300 ms moveend debounce. */
	const moveDebounceRef = useRef( null );

	/**
	 * Always-current copy of the markers attribute. Because Effect 1 has an
	 * empty dependency array, the dragend closures it registers would otherwise
	 * capture the initial (stale) markers array. This ref is updated after
	 * every render so dragend handlers always operate on fresh state.
	 *
	 * @type {React.MutableRefObject<Array>}
	 */
	const markersRef = useRef( markers );

	const blockProps = useBlockProps( {
		className: 'bflm-leaflet-map-block',
	} );

	// Keep markersRef current after every render (no dependency array = always).
	useEffect( () => {
		markersRef.current = markers;
	} );

	// ── Effect 1: Mount — initialise map ─────────────────────────────────────
	//
	// Polls for the iframe's Leaflet global, then creates the map, tile layer,
	// and marker layer group. Attaches moveend/zoomend for bi-directional sync.
	// Also adds the initial markers so they appear even before Effect 6 fires.
	// Cleanup destroys the full map instance on unmount.
	useEffect( () => {
		const container = mapContainerRef.current;
		if ( ! container ) {
			return;
		}

		const iframeWin = container.ownerDocument?.defaultView;
		if ( ! iframeWin ) {
			return;
		}

		let attempts       = 0;
		const MAX_ATTEMPTS = 20;

		/**
		 * Add all markers from markersData to a Leaflet layer group.
		 * Each marker is draggable; on drag-end the attributes are updated.
		 *
		 * @param {Object}   L           Leaflet global.
		 * @param {Object}   layerGroup  L.layerGroup instance.
		 * @param {Array}    markersData Markers array from block attributes.
		 */
		function populateLayerGroup( L, layerGroup, markersData ) {
			markersData.forEach( ( markerData, index ) => {
				const markerInstance = L.marker(
					[ markerData.lat, markerData.lng ],
					{ draggable: true }
				);

				if ( markerData.content ) {
					markerInstance.bindPopup( markerData.content );
				}

				markerInstance.on( 'dragend', ( e ) => {
					const pos     = e.target.getLatLng();
					const current = markersRef.current;
					setAttributes( {
						markers: current.map( ( m, i ) =>
							i === index
								? {
									...m,
									lat: parseFloat( pos.lat.toFixed( 6 ) ),
									lng: parseFloat( pos.lng.toFixed( 6 ) ),
								}
								: m
						),
					} );
				} );

				layerGroup.addLayer( markerInstance );
			} );
		}

		/**
		 * Poll for L and initialise the map once available.
		 */
		function tryInit() {
			if ( ! mapContainerRef.current || mapInstanceRef.current ) {
				return;
			}

			const L = iframeWin.L;

			if ( ! L ) {
				if ( ++attempts < MAX_ATTEMPTS ) {
					setTimeout( tryInit, 300 );
				} else {
					// eslint-disable-next-line no-console
					console.warn(
						'BFLM: Leaflet (L) not found in iframe after ' +
						MAX_ATTEMPTS + ' attempts.'
					);
				}
				return;
			}

			// Read tile settings injected by PHP into the iframe window.
			const config      = iframeWin.bflmConfig || {};
			const tileUrl     = config.tileUrl     || DEFAULT_TILE_URL;
			const subdomains  = config.tileSubdomains || '';
			const attribution = config.attribution || DEFAULT_ATTRIBUTION;

			// eslint-disable-next-line no-console
			console.log( 'BFLM: Initialising map. Tile URL:', tileUrl );

			const map = L.map( container, {
				scrollWheelZoom,
				zoomControl,
				attributionControl: true,
			} ).setView( [ lat, lng ], zoom );

			L.tileLayer( tileUrl, {
				attribution,
				subdomains,
				maxZoom:     19,
				crossOrigin: true,
			} ).addTo( map );

			// Marker layer group — clearing this never triggers tile reloads.
			const layerGroup = L.layerGroup().addTo( map );
			markerLayerGroupRef.current = layerGroup;

			// Add initial markers (handles the async-init case where Effect 6
			// already ran but found mapInstanceRef null and returned early).
			populateLayerGroup( L, layerGroup, markersRef.current );

			// Bi-directional sync: user pans/zooms → update block attributes.
			map.on( 'moveend zoomend', () => {
				if ( isProgrammaticMoveRef.current ) {
					return; // Triggered by setView(), not user interaction.
				}

				clearTimeout( moveDebounceRef.current );
				moveDebounceRef.current = setTimeout( () => {
					const center = map.getCenter();
					setAttributes( {
						lat:  parseFloat( center.lat.toFixed( 6 ) ),
						lng:  parseFloat( center.lng.toFixed( 6 ) ),
						zoom: map.getZoom(),
					} );
				}, 300 );
			} );

			mapInstanceRef.current = map;
			// eslint-disable-next-line no-console
			console.log( 'BFLM: Map initialised.' );

			// Force tile recalculation — needed inside the iframed editor.
			setTimeout( () => map.invalidateSize(), 100 );
		}

		tryInit();

		return () => {
			clearTimeout( moveDebounceRef.current );
			if ( mapInstanceRef.current ) {
				mapInstanceRef.current.remove();
				mapInstanceRef.current    = null;
				markerLayerGroupRef.current = null;
			}
		};
	}, [] ); // eslint-disable-line react-hooks/exhaustive-deps
	// ^ Empty deps: init/destroy only on mount/unmount.
	//   All attribute changes are handled by dedicated effects below.

	// ── Effect 2: Sync lat / lng / zoom (sidebar → map) ──────────────────────
	useEffect( () => {
		const map = mapInstanceRef.current;
		if ( ! map ) {
			return;
		}

		const center  = map.getCenter();
		const epsilon = 0.000001;
		const same    =
			Math.abs( center.lat - lat ) < epsilon &&
			Math.abs( center.lng - lng ) < epsilon &&
			map.getZoom() === zoom;

		if ( ! same ) {
			// Guard the moveend listener so it does not echo this change back.
			// setView with animate:false fires moveend synchronously, so we can
			// set and clear the flag within the same call stack.
			isProgrammaticMoveRef.current = true;
			map.setView( [ lat, lng ], zoom, { animate: false } );
			isProgrammaticMoveRef.current = false;
		}
	}, [ lat, lng, zoom ] ); // eslint-disable-line react-hooks/exhaustive-deps

	// ── Effect 3: Height changes ──────────────────────────────────────────────
	useEffect( () => {
		if ( ! mapInstanceRef.current ) {
			return;
		}
		const id = setTimeout(
			() => mapInstanceRef.current?.invalidateSize(),
			0
		);
		return () => clearTimeout( id );
	}, [ height ] );

	// ── Effect 4: Scroll-wheel zoom toggle ────────────────────────────────────
	useEffect( () => {
		const map = mapInstanceRef.current;
		if ( ! map ) {
			return;
		}
		if ( scrollWheelZoom ) {
			map.scrollWheelZoom.enable();
		} else {
			map.scrollWheelZoom.disable();
		}
	}, [ scrollWheelZoom ] );

	// ── Effect 5: Zoom control toggle ─────────────────────────────────────────
	useEffect( () => {
		const map = mapInstanceRef.current;
		if ( ! map ) {
			return;
		}
		if ( zoomControl ) {
			map.zoomControl.addTo( map );
		} else {
			map.zoomControl.remove();
		}
	}, [ zoomControl ] );

	// ── Effect 6: Sync markers (attributes → Leaflet layer group) ─────────────
	//
	// Clears the layer group and re-adds all markers whenever the attribute
	// array changes. Re-creating markers is cheap — it never triggers tile
	// reloads, unlike SSR which re-fetched all tiles on every change.
	//
	// The map/layerGroup may not exist yet on the first run (async Leaflet init).
	// That is handled by Effect 1's populateLayerGroup() call inside tryInit().
	useEffect( () => {
		const map        = mapInstanceRef.current;
		const layerGroup = markerLayerGroupRef.current;
		if ( ! map || ! layerGroup ) {
			return;
		}

		const iframeWin = mapContainerRef.current?.ownerDocument?.defaultView;
		const L         = iframeWin?.L;
		if ( ! L ) {
			return;
		}

		layerGroup.clearLayers();

		markers.forEach( ( markerData, index ) => {
			const markerInstance = L.marker(
				[ markerData.lat, markerData.lng ],
				{ draggable: true }
			);

			if ( markerData.content ) {
				markerInstance.bindPopup( markerData.content );
			}

			markerInstance.on( 'dragend', ( e ) => {
				const pos     = e.target.getLatLng();
				const current = markersRef.current;
				setAttributes( {
					markers: current.map( ( m, i ) =>
						i === index
							? {
								...m,
								lat: parseFloat( pos.lat.toFixed( 6 ) ),
								lng: parseFloat( pos.lng.toFixed( 6 ) ),
							}
							: m
					),
				} );
			} );

			layerGroup.addLayer( markerInstance );
		} );
	}, [ markers ] ); // eslint-disable-line react-hooks/exhaustive-deps

	// ── Marker attribute helpers ──────────────────────────────────────────────

	/**
	 * Append a new marker at the current map centre (or default lat/lng).
	 */
	function handleAddMarker() {
		const map    = mapInstanceRef.current;
		const center = map ? map.getCenter() : { lat, lng };
		setAttributes( {
			markers: [
				...markers,
				{
					lat:     parseFloat( center.lat.toFixed( 6 ) ),
					lng:     parseFloat( center.lng.toFixed( 6 ) ),
					title:   '',
					content: '',
				},
			],
		} );
	}

	/**
	 * Merge an update object into a single marker by index.
	 *
	 * @param {number} index   Marker index.
	 * @param {Object} updates Key/value pairs to merge.
	 */
	function handleUpdateMarker( index, updates ) {
		setAttributes( {
			markers: markers.map( ( m, i ) =>
				i === index ? { ...m, ...updates } : m
			),
		} );
	}

	/**
	 * Remove a marker by index.
	 *
	 * @param {number} index Marker index.
	 */
	function handleRemoveMarker( index ) {
		setAttributes( {
			markers: markers.filter( ( _, i ) => i !== index ),
		} );
	}

	// ── Render ────────────────────────────────────────────────────────────────

	return (
		<>
			<InspectorControls>

				{ /* ── Map Settings panel ─────────────────────────────────── */ }
				<PanelBody
					title={ __( 'Map Settings', 'blocks-for-leaflet-map' ) }
					initialOpen={ true }
				>
					<NumberControl
						label={ __( 'Latitude', 'blocks-for-leaflet-map' ) }
						value={ lat }
						onChange={ ( value ) =>
							setAttributes( { lat: parseFloat( value ) || 0 } )
						}
						step={ 0.0001 }
						__next40pxDefaultSize
					/>
					<NumberControl
						label={ __( 'Longitude', 'blocks-for-leaflet-map' ) }
						value={ lng }
						onChange={ ( value ) =>
							setAttributes( { lng: parseFloat( value ) || 0 } )
						}
						step={ 0.0001 }
						__next40pxDefaultSize
					/>
					<RangeControl
						label={ __( 'Zoom Level', 'blocks-for-leaflet-map' ) }
						value={ zoom }
						onChange={ ( value ) => setAttributes( { zoom: value } ) }
						min={ 1 }
						max={ 20 }
						__nextHasNoMarginBottom
					/>
					<NumberControl
						label={ __( 'Height (px)', 'blocks-for-leaflet-map' ) }
						value={ height }
						onChange={ ( value ) =>
							setAttributes( {
								height: parseInt( value, 10 ) || 400,
							} )
						}
						min={ 100 }
						step={ 10 }
						__next40pxDefaultSize
					/>
					<ToggleControl
						label={ __(
							'Scroll Wheel Zoom',
							'blocks-for-leaflet-map'
						) }
						checked={ scrollWheelZoom }
						onChange={ ( value ) =>
							setAttributes( { scrollWheelZoom: value } )
						}
						__nextHasNoMarginBottom
					/>
					<ToggleControl
						label={ __( 'Zoom Control', 'blocks-for-leaflet-map' ) }
						checked={ zoomControl }
						onChange={ ( value ) =>
							setAttributes( { zoomControl: value } )
						}
						__nextHasNoMarginBottom
					/>
				</PanelBody>

				{ /* ── Markers panel ────────────────────────────────────────── */ }
				<PanelBody
					title={ sprintf(
						/* translators: %d: number of markers on the map. */
						__( 'Markers (%d)', 'blocks-for-leaflet-map' ),
						markers.length
					) }
					initialOpen={ false }
				>
					<Button
						variant="secondary"
						onClick={ handleAddMarker }
						style={ { width: '100%', marginBottom: '12px', justifyContent: 'center' } }
					>
						{ __( '+ Add Marker at Center', 'blocks-for-leaflet-map' ) }
					</Button>

					{ markers.map( ( marker, index ) => (
						<PanelBody
							key={ index }
							title={ sprintf(
								/* translators: %d: 1-based marker number. */
								__( 'Marker %d', 'blocks-for-leaflet-map' ),
								index + 1
							) }
							initialOpen={ false }
						>
							<NumberControl
								label={ __( 'Latitude', 'blocks-for-leaflet-map' ) }
								value={ marker.lat }
								onChange={ ( value ) =>
									handleUpdateMarker( index, {
										lat: parseFloat( value ) || 0,
									} )
								}
								step={ 0.0001 }
								__next40pxDefaultSize
							/>
							<NumberControl
								label={ __( 'Longitude', 'blocks-for-leaflet-map' ) }
								value={ marker.lng }
								onChange={ ( value ) =>
									handleUpdateMarker( index, {
										lng: parseFloat( value ) || 0,
									} )
								}
								step={ 0.0001 }
								__next40pxDefaultSize
							/>
							<TextControl
								label={ __( 'Title', 'blocks-for-leaflet-map' ) }
								value={ marker.title || '' }
								onChange={ ( value ) =>
									handleUpdateMarker( index, { title: value } )
								}
								__next40pxDefaultSize
							/>
							<TextareaControl
								label={ __(
									'Popup Content',
									'blocks-for-leaflet-map'
								) }
								help={ __(
									'HTML is supported.',
									'blocks-for-leaflet-map'
								) }
								value={ marker.content || '' }
								onChange={ ( value ) =>
									handleUpdateMarker( index, { content: value } )
								}
								rows={ 3 }
							/>
							<Button
								variant="link"
								isDestructive
								onClick={ () => handleRemoveMarker( index ) }
								style={ { marginTop: '4px' } }
							>
								{ __( 'Remove Marker', 'blocks-for-leaflet-map' ) }
							</Button>
						</PanelBody>
					) ) }
				</PanelBody>

			</InspectorControls>

			<div
				{ ...blockProps }
				onMouseDown={ ( e ) => e.stopPropagation() }
			>
				<div
					ref={ mapContainerRef }
					className="bflm-map-canvas"
					style={ { height: height + 'px' } }
				/>
			</div>
		</>
	);
}
